// <auto-generated />
namespace BlogSystem.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatetocloud : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetocloud));
        
        string IMigrationMetadata.Id
        {
            get { return "202405231737384_update to cloud"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
